[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "cd ../.. && npm install"
]

[phases.build]
cmds = [
  "cd apps/web && rm -rf .next",
  "cd ../.. && npm run build:web",
  "chmod +x fix-routes-manifest.sh",
  "./fix-routes-manifest.sh"
]

[start]
cmd = "cd ../.. && npm run start:web"
