[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "cd ../.. && npm install"
]

[phases.build]
cmds = [
  "cd ../.. && npm run build:api"
]

[start]
cmd = "cd ../.. && npm run start:api"
